language: ruby
rvm:
- 2.1

before_script:
- chmod +x ./script/cibuild
- bundle install

script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master  # test the master branch

notifications:
  email: rufermarc@gmail.com

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer