language: ruby
rvm:
- 2.1

# branch whitelist
branches:
  only:
  - master  # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_script:
  bundle update
  chmod +x cibuild

script: script/cibuild

notifications:
  email: rufermarc@gmail.com