# Jekyll configuration

title: rufer7.github.io
permalink: /blog/:categories/:title.html
highlighter: pygments
github: [Repository metadata]
timezone: Europe/Zurich
exclude: [jekyll_serve.bat, jekyll_update.bat]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


# Site owner

owner:
  name: Marc Rufer
  avatar: http://www.gravatar.com/avatar/1b0197d9f527c985a9ffe2c4f32086df
  bio: "Software engineer"
  email: rufermarc@gmail.com
  disqus-shortname: Rufer
  facebook: #username
  twitter: #username
  google:
    plus: MarcRufer
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: rufer7
  stackoverflow: 2796003/rufer7
  linkedin: #username
  instagram: #username