# Jekyll configuration

title: blog.rufer.be
permalink: /blog/:categories/:title.html
highlighter: pygments
github: [Repository metadata]
timezone: Europe/Zurich
exclude: [jekyll_serve.bat, jekyll_update.bat]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


# Site owner

owner:
  name: Marc Rufer
  avatar: http://www.gravatar.com/avatar/1b0197d9f527c985a9ffe2c4f32086df
  email:
  disqus-shortname: rufer7
  facebook: #username
  twitter: rufer_13
  google:
    plus: MarcRufer
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: rufer7
  stackoverflow: 2796003/rufer7
  xing:
  linkedin: marcrufer
  instagram: #username


# RSS-Feed

name: Rufers Blog
description: This is my personal blog based on GitHub Pages. Here I publish blog posts about different topics concerning computer science. Furthermore I will use it as a personal knowledge base.
url: http://rufer7.github.io